import type {Metadata} from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/app/components/Shared/Header";
import Footer from "@/app/components/Shared/Footer";
import {AppRouterCacheProvider} from "@mui/material-nextjs/v13-appRouter";
import ScreenWrapper from "@/app/components/Shared/ScreenWrapper";

const geistSans = localFont({
    src: "./fonts/GeistVF.woff",
    variable: "--font-geist-sans",
    weight: "100 900",
});
const geistMono = localFont({
    src: "./fonts/GeistMonoVF.woff",
    variable: "--font-geist-mono",
    weight: "100 900",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body
            className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
        <Header/>
        <AppRouterCacheProvider>
            <ScreenWrapper>
                {children}
            </ScreenWrapper>
            <Footer/>
        </AppRouterCacheProvider>
        </body>
        </html>
    );
}
